### ISSUE TITLE
I'm not Okay.

### ISSUE THREAD

**Issue by ijehyunpark** [Kim-Woojeong/database#2]
I'm Okay.
Your Problem.
Thank you ㅋ

_Originally posted by @DongJoon-Lee in https://github.com/Kim-Woojeong/database/issues/1#issuecomment-554855381_

**Comment by notmybussiness** [comment]
me toooooo

**Comment by notmybussiness** [comment]
no mac fuck mac

**Comment by DongJoon-Lee** [comment]
어그로 out.
You're not appropriate to our Project.
It's okay i my mac os. Please buy macbook and try again.
Thanks.
